[plugin]
repository = "https://github.com/Pistachio-dev/Faded-Roll-Fixer"
commit = "https://github.com/Pistachio-dev/Faded-Roll-Fixer"
owners = ["Pistachio-dev"]
project_path = "FadedRollFixer"
changelog = "Initial Release"

