[plugin]
repository = "https://github.com/Pistachio-dev/Faded-Roll-Fixer.git"
commit = "58793a33c7e681d228be2ade0cf9674030321fbc"
owners = ["Pistachio-dev"]
project_path = "FadedRollFixer"
changelog = "Initial Release"

